---
hostname: minecraft

firewall_tcp_ports:
  - "{{ sshd_config_port }}"
  - "25565" # minecraft query port

minecraft_cron_messages:
  - name: "2000"
    file_name: "2000"
    hour: "20"
    minute: "00"
    message: "â³ 30 minutes left ğŸ˜¿"
  - name: "2020"
    file_name: "2020"
    hour: "20"
    minute: "20"
    message: "â³ 10 minutes left"
  - name: "2025"
    file_name: "2025"
    hour: "20"
    minute: "25"
    message: "âŒ› 5 minutes left ğŸ™€"
  - name: "2030"
    file_name: "2030"
    hour: "20"
    minute: "30"
    message: "ğŸ”” Time's up! ğŸ””"


remove_base_packages: true
remove_cis_packages: true
remove_desktop_packages: true

hardening_disable_filesystems:
  - cramfs
  - freevxfs
  - jffs2
  - hfs
  - hfsplus
  - squashfs
  - udf
  # - vfat  # raspberry pi uses vfat for boot partition
